### ISSUE TITLE
业务：参数管理

### ISSUE THREAD

**Issue by XiaogangSu** [guangmushikong/AirPhotoPlanner#2]
细化参数管理：主要分成两部分，一部分是固定参数：所有航区使用相同的值，如机场位置、焦距、相片高等 另一部分是摄区参数，根据摄区的不同，所对应的值也不相同，如基准面高度

**Comment by tjmiaowang** [comment]
缺少比例尺 或者 航高参数

**Comment by XiaogangSu** [comment]
参数设置界面，地面分辨率增加单位说明

**Comment by tjmiaowang** [comment]
在 issue #16 中继续完成，多航区参数自动导入。
