### ISSUE TITLE
业务：地图窗口：航区导入

### ISSUE THREAD

**Issue by XiaogangSu** [guangmushikong/AirPhotoPlanner#4]
打开航区时，地图自动移动到航区位置，同时设置合适的缩放比例，能清晰看到所有摄区

**Comment by tjmiaowang** [comment]
请描述一下

**Comment by tjmiaowang** [comment]
2月9，测试问题一，导入两个测试航区，再点 “导入文件”按钮，自动变成三个摄区
![1](https://user-images.githubusercontent.com/13048706/36023090-432963cc-0dc6-11e8-9112-c39fac9dac9d.JPG)

**Comment by tjmiaowang** [comment]
疑问：如何指定航区顺序

**Comment by XiaogangSu** [comment]
通过直接拖动文件的方式调整设置航区规划顺序

**Comment by XiaogangSu** [comment]
问题一通过
问题二未解决

**Comment by XiaogangSu** [comment]
修改建议（二选一）：
（1）算法修改，自动搜索近距离航区进行路径规划
（2）在界面处可调整航区顺序
