### ISSUE TITLE
数据管理：底图包管理

### ISSUE THREAD

**Issue by tjmiaowang** [guangmushikong/AirPhotoPlanner#5]
软件自带基本底图，目前计划包含世界地图0-4层，中国全境6-12层 另外是精细数据包，以文件的形式导入

**Comment by tjmiaowang** [comment]
1. 图层分开
2. 设置数据根路径
![airphotoplanner_mapdata_fileroute](https://user-images.githubusercontent.com/13048706/36135591-23321fe2-10c7-11e8-8bf7-cd7e16e3612e.jpg)
数据文件夹定义与服务器端一致，加载自定义数据时，图层名称在Data Description file中定义

**Comment by tjmiaowang** [comment]
数据不足，补齐

**Comment by tjmiaowang** [comment]
命名与服务端一致

**Comment by XiaogangSu** [comment]
本周数据补齐，Data/SatImage/google_tiles/test_world/；Data/SatImage/google_tiles/test_china/；Data/DTM/china/color_shade.zip

**Comment by XiaogangSu** [comment]
由于目前软件只支持png格式图片，所以只补齐了“Data/DTM/china/color_shade.zip”数据，已把解压后程序与数据放到百度云盘路径“Release/Win32/PhotoPlanner/AirPhotoPlanner_国博”。

**Comment by tjmiaowang** [comment]
安卓版实现。
